### ISSUE TITLE
bug on new attribute quickie creation

### ISSUE THREAD

**Issue by diroots** [HugoHasenbein/redmine_attribute_quickies#1]
Hello, I just activated the module on a redmine

I activated the module on a new projet, check the view and manage attribute quickies permissions for the project administrator, and then go to project configuration to create a new one : 

/projects/attr-quicki/settings/attribute_quickies/new

I get a : 
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

here is the error trace in production log : 

> Started GET "/projects/attr-quicki/settings/attribute_quickies/new" for 37.166.30.149 at 2020-01-24 14:42:36 +0100
> Processing by AttributeQuickiesController#new as HTML
>   Parameters: {"id"=>"attr-quicki"}
>   Current user: admin (id=1)
>   Rendered plugins/redmine_attribute_quickies/app/views/attribute_quickies/_issue_attributes_form.html.erb (0.7ms)
>   Rendered plugins/that_issue_reply_button/app/views/issues/_reply.html.erb (6.4ms)
>   Rendered plugins/redmine_attribute_quickies/app/views/attribute_quickies/_form.html.erb (119.4ms)
>   Rendered plugins/redmine_attribute_quickies/app/views/attribute_quickies/new.html.erb within layouts/base (121.4ms)
> Completed 500 Internal Server Error in 181ms (ActiveRecord: 43.6ms)
> 
> ActionView::Template::Error (No route matches {:action=>"edit", :controller=>"issues", :id=>nil} missing required keys: [:id]):
>      7:           $('<a>', {
>      8:             'class': 'icon icon-reply',
>      9:             text: '<%= l(:button_reply) %>',
>     10:             href: '<%= edit_issue_path(@issue) %>',
>     11:             click: function() {
>     12:               $('#update .edit_issue .box > fieldset.tabular').hide();
>     13:               showAndScrollTo('update', 'issue_notes');
>   plugins/that_issue_reply_button/app/views/issues/_reply.html.erb:10:in `block in _plugins_that_issue_reply_button_app_views_issues__reply_html_erb__3983741600059268265_70154218498400'
>   plugins/that_issue_reply_button/app/views/issues/_reply.html.erb:1:in `_plugins_that_issue_reply_button_app_views_issues__reply_html_erb__3983741600059268265_70154218498400'
>   lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
>   lib/redmine/hook/view_listener.rb:57:in `map'
>   lib/redmine/hook/view_listener.rb:57:in `block in render_on'
>   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
>   lib/redmine/hook.rb:61:in `each'
>   lib/redmine/hook.rb:61:in `block in call_hook'
>   lib/redmine/hook.rb:58:in `tap'
>   lib/redmine/hook.rb:58:in `call_hook'
>   lib/redmine/hook.rb:96:in `call_hook'
>   plugins/redmine_attribute_quickies/app/views/attribute_quickies/_form.html.erb:114:in `block in _plugins_redmine_attribute_quickies_app_views_attribute_quickies__form_html_erb__4275294704115866454_70154220999000'
>   app/helpers/application_helper.rb:1197:in `labelled_fields_for'
>   plugins/redmine_attribute_quickies/app/views/attribute_quickies/_form.html.erb:1:in `_plugins_redmine_attribute_quickies_app_views_attribute_quickies__form_html_erb__4275294704115866454_70154220999000'
>   plugins/redmine_attribute_quickies/app/views/attribute_quickies/new.html.erb:6:in `block in _plugins_redmine_attribute_quickies_app_views_attribute_quickies_new_html_erb__822617546289127613_70154221184020'
>   plugins/redmine_attribute_quickies/app/views/attribute_quickies/new.html.erb:2:in `_plugins_redmine_attribute_quickies_app_views_attribute_quickies_new_html_erb__822617546289127613_70154221184020'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**redmine infos :** 

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.3
  clipboard_image_paste          1.13
  computed_custom_field          1.0.6
  custom_users_as_assignees      0.0.3
  customfield_checkbox_utility   0.0.2
  mega_calendar                  1.7.1
  redmine_attribute_quickies     1.0.2
  redmine_checklists             3.1.11
  redmine_ckeditor               1.1.5
  redmine_editauthor             0.11.0
  redmine_favorite_projects      2.1.0
  redmine_impersonate            1.0.0
  redmine_issue_badge            0.0.7
  redmine_issue_tabs             1.3.2
  redmine_issues_tree            0.0.12
  redmine_lightbox2              0.4.3
  redmine_logs                   0.1.1
  redmine_my_page                0.1.13
  redmine_slack                  0.2
  redmine_user_import            0.1.0
  redmine_workflow_hidden_fields 0.5.0
  that_issue_reply_button        0.0.1
  unread_issues                  2.2.3

**Comment by diroots** [comment]
ok, that's an incompatibility bug with the plugin https://github.com/thatcompany/that_issue_reply_button all is working if Idesactivate this plugin
